[project]
name = "phasedibd"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.8"
numpy = "1.20.2"
pandas = "1.2.3"
cython = "0.29.23"
pip = "*"
wheel = "*"
setuptools-scm = "*"
